#! /bin/bash
a=${1:-linux}
b=${2:-10}
[ $b -gt 10 ] && b=10
curl -s "http://tieba.baidu.com/f?kw=$a" | iconv -f GBK -t UTF-8 | grep '<a href="/p/[0-9]*"' | sed 's/<a href="//g;s/ target.*//g;s/" title="/ /g;s/"$//g;s/\/p\///;s:</a>::g;s/\t//g;s/&quot;/"/g;s/&lt;/</g;s/&gt;/>/g;s/&amp;/&/g;s/&reg;/®/g;s/&copy;/©/g;s/&trade;/™/g' | head -$b
